Decorate class
braincee/School-library-project pull request #2
Opened 2022-07-22 15:29 UTC by braincee

- I created a class Nameable.
- I implemented a method called correct_name that will raise a NotImplementedError.
- I turned your Person class to Nameable
- I made sure that my Person class inherits from Nameable
I made sure that this class has a method correct_name implemented. It should simply return the name attribute.

-  Prepare base Decorator

- I made sure that it inherits from Nameable.
- In the constructor, I assign a nameable object from params to an instance variable.
- I implemented the correct_name method that returns the result of the correct_name method of the @nameable.

-  Prepare CapitalizeDecorator and TrimmerDecorator

- For the CapitalizeDecorator:
- I created a class that inherits from the base Decorator class.
- implemented a method correct_name that capitalises the output of @nameable.correct_name.
- For the TrimmerDecorator:
- I created a class that inherits from the base Decorator class.
- I implemented a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

2022-07-22 16:20 UTC, julie-ify requested changes
## Hi @braincee,

Good job so far!

## Highlights!
- GitFlow ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 16:20 UTC, julie-ify commented on base_decorator.rb
> +    super()
- [ ] I received the attached error when I ran your program, and the error was about the default parameter you passed to the initialize method as an instance of the `Nameable` class, which is not supposed. Kindly remove the default value and pass `nameable` without the default value.

- [ ] Also, there is no use of the `super()` call you to have here too. Kindly remove it.

<img width="645" alt="chrome_IF8oZB8Wiu" src="https://user-images.githubusercontent.com/81468675/180480897-4cf6583a-8190-4d12-95e3-a6ba1391828b.png">

2022-07-22 16:43 UTC, julie-ify approved these changes
Hi @braincee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 16:43 UTC, julie-ify commented on person.rb
> +  end
- [ ] **[OPTIONAL]** I forgot to mention in the first review that you should not make this method private. I got an error saying that I'm trying to access the private method `correct_name` in the person class. So please kindly make this method `public` before your next milestone.

2022-07-22 17:00 UTC, merged

2022-11-12 11:36 UTC, braincee commented
Thanks very much, @julie-ify 


![thank-you-thank-you-thank-you](https://user-images.githubusercontent.com/78104544/201472114-da33c015-f10c-4035-b19c-238ca1c8226d.gif)