Preserve data
braincee/School-library-project pull request #8
Opened 2022-07-27 08:46 UTC by ericmahare

### n this section we did the following : -

- [ ] Preserved data to the json files after exiting the app

2022-07-27 10:04 UTC, medaminedev66 requested changes
Hi @braincee and @ericmahare  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The data is saved into JSON files after closing the app.
- all data is loaded from JSON files after starting the app.
Great job 👏

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 10:04 UTC, medaminedev66 commented on read_data.rb
> +end
- [ ] You should handle the case when one or more of the JSON files are missing. I tried to remove the `people..json, retals.json, books.json` files. When I run your app, it shows the following error:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/77190203/181219724-87edd4f2-b810-40f8-a934-1925c421d62c.png">

Please make sure that if one of the files is missing, your app will create a new one with an empty array and save the data there when the app is exited.

2022-07-27 11:39 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @ericmahare & @braincee, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 13:51 UTC, merged

2022-11-12 11:41 UTC, braincee commented
Thanks very much, @sja-thedude @medaminedev66 

![thank-you-thankyou](https://user-images.githubusercontent.com/78104544/201472304-f7dacc9c-e9b8-4e7a-b9ff-6cb1a7c669db.gif)